name: Build and Test
on: [push]
env:
  CI: true
  DISPLAY: ":99.0"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare display for linux
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Main
        run: |
          npm ci
          npm run build
          npm test
          ./e2e-test.sh
      - name: npm pack for VSCode Extension
        working-directory: ./vscode-dsl/server
        run: |
          npm pack ../..
      - name: VSCode Extension
        working-directory: ./vscode-dsl
        run: |
          npm ci
          npm run compile
          npm test
          npm run package
